function:
  name: ${self:service}-${self:provider.stage}-QueryErrorLogs
  description: Query error logs, triggered by an event
  handler: src.entrypoints.query_error_logs.main.handler
  timeout: 300
  events:
    - schedule:
        rate: ${self:custom.configs.MonitoringConfigs.CloudwatchLogs.Schedule}
        enabled: ${ternary(${self:custom.configs.MonitoringConfigs.CloudwatchLogs.State}, enabled, true, false)}
  environment:
    POWERTOOLS_SERVICE_NAME: events
    CW_INSIGHTS_QUERY_STRING: ${self:custom.configs.MonitoringConfigs.CloudwatchLogs.Query}
    CW_INSIGHTS_QUERY_DURATION: 300
    CW_INSIGHTS_QUERY_TIMEOUT: 15
    CW_LOGS_DELIVERY_LATENCY: 15
