from typing import Protocol

from src.domain.models import AgentQueryResult, Event, EventQueryResult
from src.domain.models.agent import Agent, UpdateAgentDTO
from src.domain.models.event import ListEventsDTO


class IAgentRepository(Protocol):
    async def get(self, id: str) -> Agent: ...

    async def list(self) -> AgentQueryResult: ...

    async def create(self, entity: Agent) -> None: ...

    async def update(self, id: str, dto: UpdateAgentDTO) -> None: ...

    async def delete(self, id: str) -> None: ...

    async def exists(self, id: str) -> bool: ...


class IEventRepository(Protocol):
    async def get(self, id: str) -> Event: ...

    async def list(self, dto: ListEventsDTO | None = None) -> EventQueryResult: ...

    async def create(self, entity: Event) -> None: ...

    async def delete(self, id: str) -> None: ...
