exclude: 'docs|node_modules|migrations|data|.tox|.idea|venv|.serverless|.aws-sam'
fail_fast: true
default_stages: [ pre-commit ]
default_install_hook_types: [ pre-commit, pre-push, commit-msg ]

repos:
  # https://pre-commit.com/#plugins
  # pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Security
      - id: detect-aws-credentials
      - id: detect-private-key
      # Detector
      - id: check-json
      - id: check-case-conflict
      - id: check-merge-conflict
      # Formatter
      - id: trailing-whitespace
        stages: [ pre-commit ]
      - id: end-of-file-fixer
        stages: [ pre-commit ]

  # Python code formatter
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.13

  # sort imports alphabetically, and automatically separated into sections and by type
  - repo: https://github.com/timothycrosley/isort
    rev: 6.0.0
    hooks:
      - id: isort
        language_version: python3.13
        stages: [ pre-commit ]

  # compliance to PEP8
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        language_version: python3.13

  # security
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: [ "-x", "tests,local" ]
