service: teligent-master

stages:
  default:
    resolvers:
      aws-account:
        type: aws
        profile: ${self:custom.configs.Profile}
        region: ${opt:region, self:custom.configs.Region}

provider:
  name: aws
  resolver: aws-account
  stage: ${opt:stage, "dev"}
  stackName: ${self:service}-${self:provider.stage}

  # default tags for all resources
  stackTags:
    Owner: ${self:service}
    Environment: ${self:provider.stage}
  tags: ${self:provider.stackTags}

  # S3 bucket where the artifact is stored
  deploymentBucket:
    name: ${self:custom.configs.S3.DeploymentBucket.Name}

  # config lambda functions
  runtime: python3.12
  logRetentionInDays: ${self:custom.configs.Lambda.LogRetentionInDays}
  memorySize: 256
  timeout: 10
  role: LambdaFunctionRole
  layers:
    - !Ref PythonRequirementsLambdaLayer

  # Default environment for lambda functions
  environment:
    STAGE: ${self:provider.stage}
    POWERTOOLS_LOG_LEVEL: ${self:custom.configs.Lambda.Environment.LOG_LEVEL}
    # references to resources in this template
    DYNAMODB_TABLE: !Ref DynamoDBTable
    AWS_REGION: ${aws:region}

plugins:
  - serverless-plugin-utils
  - serverless-python-requirements

useDotenv: true

custom:
  # load the configuration corresponding to a specific $stage
  configs: ${file(infra/master/configs/${self:provider.stage}.yml)}
  # plugins
  pythonRequirements: ${file(infra/master/plugins/python_requirements.yml):pythonRequirements}

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - "!./**"

functions:
  HandleMonitoringEvents: ${file(infra/master/functions/HandleMonitoringEvents.yml):function}
  DailyReport: ${file(infra/master/functions/DailyReport.yml):function}
  # API -------------------------------------------------------------------------
  # Events
  GetEvent: ${file(infra/master/functions/api/GetEvent.yml):function}
  ListEvents: ${file(infra/master/functions/api/ListEvents.yml):function}
  UpdateEvent: ${file(infra/master/functions/api/UpdateEvent.yml):function}

resources:
  # -----------------------------------------------------------------------------
  Parameters:
    Stage:
      Type: String
      Default: ${self:provider.stage}
      AllowedValues: [ neos ]
  # -----------------------------------------------------------------------------
  Resources:
    # IAM
    LambdaFunctionRole: ${file(infra/master/resources/iam.yml):LambdaFunctionRole}
    LambdaFunctionPolicy: ${file(infra/master/resources/iam.yml):LambdaFunctionPolicy}
    EventBridgeRole: ${file(infra/master/resources/iam.yml):EventBridgeRole}
    EventBridgePolicy: ${file(infra/master/resources/iam.yml):EventBridgePolicy}
    # EventBridge
    MonitoringEventBus: ${file(infra/master/resources/event_bridge.yml):MonitoringEventBus}
    MonitoringEventRule: ${file(infra/master/resources/event_bridge.yml):MonitoringEventRule}
    # SQS
    MonitoringDLQ: ${file(infra/master/resources/sqs.yml):MonitoringDLQ}
    # DynamoDB
    DynamoDBTable: ${file(infra/master/resources/dynamodb.yml):DynamoDBTable}

  # -----------------------------------------------------------------------------
  Outputs: { }
