service: teligent-agent

stages:
  default:
    resolvers:
      aws-account:
        type: aws
        profile: ${self:custom.configs.Profile}
        region: ${opt:region, self:custom.configs.Region}

provider:
  name: aws
  resolver: aws-account
  stage: ${opt:stage, "neos"}
  stackName: ${self:service}-${self:provider.stage}

  # default tags for all resources
  stackTags:
    Owner: ${self:service}
    Environment: ${self:provider.stage}
  tags: ${self:provider.stackTags}

  # deployment
  deploymentBucket:
    name: ${self:custom.configs.S3.DeploymentBucket.Name}
  iam:
    deploymentRole: ${self:custom.configs.IAM.DeploymentRole}

  # config lambda functions
  runtime: python3.12
  logRetentionInDays: ${self:custom.configs.Lambda.LogRetentionInDays}
  memorySize: 256
  timeout: 10
  role: LambdaFunctionRole
  layers:
    - !Ref PythonRequirementsLambdaLayer

  # Default environment for lambda functions
  environment:
    STAGE: ${self:provider.stage}
    POWERTOOLS_LOG_LEVEL: ${self:custom.configs.Lambda.Environment.LOG_LEVEL}
    # references to resources in this template

plugins:
  - serverless-python-requirements

useDotenv: true

custom:
  # load the configuration corresponding to a specific $stage
  configs: ${file(infra/agent/configs/${self:provider.stage}.yml)}
  # plugins
  pythonRequirements: ${file(infra/agent/plugins/python_requirements.yml):pythonRequirements}

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - "!./**"

functions:
  QueryErrorLogs: ${file(infra/agent/functions/QueryErrorLogs.yml):function}

resources:
  # -----------------------------------------------------------------------------
  Parameters:
    Stage:
      Type: String
      Default: ${self:provider.stage}
      AllowedValues: [neos]
  # -----------------------------------------------------------------------------
  Conditions:
    IsHealthEnabled: !Equals [ ${self:custom.configs.MonitoringConfigs.Health.Enabled}, true ]
    IsGuardDutyEnabled: !Equals [ ${self:custom.configs.MonitoringConfigs.GuardDuty.Enabled}, true ]
    IsCloudwatchLogsEnabled: !Equals [ ${self:custom.configs.MonitoringConfigs.CloudwatchLogs.Enabled}, true ]

  # -----------------------------------------------------------------------------
  Resources:
    # IAM
    LambdaFunctionRole: ${file(infra/agent/resources/iam.yml):LambdaFunctionRole}
    LambdaFunctionPolicy: ${file(infra/agent/resources/iam.yml):LambdaFunctionPolicy}
    EventBridgeRole: ${file(infra/agent/resources/iam.yml):EventBridgeRole}
    EventBridgePolicy: ${file(infra/agent/resources/iam.yml):EventBridgePolicy}
    # EventBridge
    HealthEventRule: ${file(infra/agent/resources/event_bridge.yml):HealthEventRule}
  # -----------------------------------------------------------------------------
  Outputs: {}
