function:
  name: ${self:service}-${self:provider.stage}-CheckFirmwareVersion
  description: Check the firmware version of the device
  handler: src.handlers.update_firmware.check_firmware_version.main.handler
  timeout: 60
  package:
    patterns:
      - src/handlers/update_firmware/check_firmware_version/*.py
      - src/models/*.py
      - src/repositories/*.py
      - src/services/iot_core.py
      - src/services/devices.py
      - src/services/storage.py
      - src/*.py
      - "!src/templates.py"
  maximumRetryAttempts: 0
  events:
    - eventBridge:
        schedule: cron(0 15 * * ? *) # every day at midnight (00:00) JST.
  vpc:
    securityGroupIds: ${self:custom.VPC.SecurityGroupIds}
    subnetIds: ${self:custom.VPC.PrivateSubnetIds}
  environment:
    FUNTION_NAME: ${self:service}-${self:provider.stage}-CheckFirmwareVersion
