function:
  name: ${self:service}-${self:provider.stage}-PruneStatistics
  description: Delete Statistic items that have sensor_time older than 7 days
  handler: src.handlers.prune_statistics.main.handler
  package:
    patterns:
      - src/handlers/prune_statistics/*.py
      - src/models/*.py
      - src/repositories/*.py
      - src/*.py
      - "!src/templates.py"
  maximumRetryAttempts: 0
  events:
    - eventBridge:
        schedule: cron(0 0 * * ? *) # every day at midnight (00:00).
  vpc:
    securityGroupIds: ${self:custom.VPC.SecurityGroupIds}
    subnetIds: ${self:custom.VPC.PrivateSubnetIds}
  environment:
    FUNTION_NAME: ${self:service}-${self:provider.stage}-PruneStatistics
  timeout: 900
