default:
  stage: local
  region: us-east-1

# AWS Services
S3:
  DeploymentBucket:
    name: denaribots-deployment

Lambda:
  environment:
    LOG_LEVEL: DEBUG
  logRetentionInDays: 7

DynamoDB:
  BillingMode: PAY_PER_REQUEST

  # only for PROVISIONED mode
  RCU: 0
  WCU: 0
  AutoScale:
    Enable: false
    RCU:
      min: 0
      max: 0
    WCU:
      min: 0
      max: 0
    TargetUtilization: 0

VPC:
  PrivateSubnetIds:
    - subnet-123
    - subnet-123
    - subnet-123
  SecurityGroupIds:
    - sg-123

# Separate plugins for different environments
plugins:
  - ./serverless/plugins/localRefs.js
  - serverless-plugin-conditional-functions
  - serverless-localstack
  - serverless-python-requirements
  - serverless-offline
