default:
  stage: prod
  region: ap-northeast-1
  accountId: 487740830288

# AWS Services
S3:
  DeploymentBucket:
    name: denaribots-prod-deployment

Lambda:
  environment:
    LOG_LEVEL: INFO
  logRetentionInDays: 90
  versionRetentionNumber: 10

DynamoDB:
  BillingMode: PROVISIONED

  # only for PROVISIONED mode
  RCU: 20
  WCU: 20
  AutoScale:
    Enable: true
    RCU:
      min: 20
      max: 50
    WCU:
      min: 20
      max: 50
    TargetUtilization: 70 # scale when CPU utilization reach 70%

VPC:
  PrivateSubnetIds:
    - subnet-0b1dbd02b0b208f45
    - subnet-0fbde4554f065eeb1
    - subnet-02963b558a70c53dc
  SecurityGroupIds:
    - sg-0233abd39b0c24f0e

# Separate plugins for different environments
plugins:
  - ./serverless/plugins/validateDeployment.js
  - serverless-plugin-conditional-functions
  - serverless-python-requirements
  - serverless-prune-versions
