default:
  stage: stg
  region: ap-northeast-1
  accountId: 393089591757

# AWS Services
S3:
  DeploymentBucket:
    name: denaribots-stg-deployment

Lambda:
  environment:
    LOG_LEVEL: DEBUG
  logRetentionInDays: 365
  versionRetentionNumber: 10

DynamoDB:
  BillingMode: PROVISIONED

  # only for PROVISIONED mode
  RCU: 10
  WCU: 20
  AutoScale:
    Enable: true
    RCU:
      min: 10
      max: 20
    WCU:
      min: 20
      max: 30
    TargetUtilization: 70 # scale when CPU utilization reach 70%

VPC:
  PrivateSubnetIds:
    - subnet-01a9b492a15c1058f
    - subnet-0c697f1b77f166e04
    - subnet-0002d8cd2d5c0c518
  SecurityGroupIds:
    - sg-0a71ab39a6c241955

# Separate plugins for different environments
plugins:
  - ./serverless/plugins/validateDeployment.js
  - serverless-plugin-conditional-functions
  - serverless-python-requirements
  - serverless-prune-versions
