function:
  name: ${self:service}-${self:provider.stage}-QueryErrorLogs
  description: Query error logs, triggered by an event
  handler: src.handlers.agent.query_error_logs.main.handler
#  events:
#    - schedule:
#        rate: ${self:custom.monitoringConfigs.CloudwatchLogs.Default.Schedule}
#        enabled: ${ternary(self:custom.monitoringConfigs.CloudwatchLogs.State, enabled, true, false)}
  package:
    patterns:
      - src/handlers/agent/query_error_logs/*.py
  environment:
    POWERTOOLS_SERVICE_NAME: events
