DynamoDBTable:
  Type: AWS::DynamoDB::Table
  # DeletionPolicy: Retain
  UpdateReplacePolicy: Retain
  Properties:
    KeySchema:
      - AttributeName: pk
        KeyType: HASH
      - AttributeName: sk
        KeyType: RANGE
    AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      - AttributeName: sk
        AttributeType: S
    BillingMode: PAY_PER_REQUEST
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    TimeToLiveSpecification:
      AttributeName: expired_at
      Enabled: true
    TableName: ${self:service}-${self:provider.stage}
