MonitoringEventBus:
  Type: AWS::Events::EventBus
  Properties:
    Name: ${self:service}-${self:provider.stage}-MonitoringEventBus
    Description: Custom EventBus for monitoring events
    Policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "AllowLambdaToPutEvents",
            "Effect": "Allow",
            "Principal": {
              "AWS": "*"
            },
            "Action": "events:PutEvents",
            "Resource": "*"
          }
        ]
      }

MonitoringEventRule:
  Type: AWS::Events::Rule
  Properties:
    Name: "${self:service}-MonitoringEventRule"
    Description: "Rule to handle monitoring events from various sources"
    EventBusName: !Ref MonitoringEventBus
    EventPattern: |
      {
        "source": [
          "aws.cloudwatch",
          "aws.guardduty",
          "aws.health",
          "monitoring.agent.cloudwatch",
          "monitoring.agent.guardduty",
          "monitoring.agent.health",
          "monitoring.agent.logs"
        ]
      }
    State: "ENABLED"
    Targets:
      - Arn: !GetAtt HandleMonitoringEventsLambdaFunction.Arn
        Id: "${self:service}-EventHandler"
        RoleArn: !GetAtt EventBridgeRole.Arn
        DeadLetterConfig:
          Arn: !GetAtt MonitoringEventRuleDLQ.Arn


DeploymentEventRule:
  Type: AWS::Events::Rule
  Properties:
    Name: "${self:service}-DeploymentEventRule"
    Description: "Rule to handle cloudformation deployment events"
    EventBusName: !Ref MonitoringEventBus
    EventPattern: |
      {
        "source": ["aws.cloudformation"],
        "detail-type": ["CloudFormation Stack Status Change"],
        "detail": {
          "stack-id": [{ "wildcard": "*stack/monitoring-agent*"}]
        }
      }
    State: "ENABLED"
    Targets:
      - Arn: !GetAtt UpdateAgentDeploymentLambdaFunction.Arn
        Id: "${self:service}-EventHandler"
        RoleArn: !GetAtt EventBridgeRole.Arn
        DeadLetterConfig:
          Arn: !GetAtt MonitoringEventRuleDLQ.Arn
