MonitoringEventRuleDLQ:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-${self:provider.stage}-MonitoringEventRuleDLQ


MonitoringEventBusDLQ:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-${self:provider.stage}-MonitoringEventBusDLQ
