Region: us-east-1
Profile: local

# AWS Services
IAM:
  DeploymentRole: arn:aws:iam::728171922033:role/teligent-DeploymentRole

S3:
  DeploymentBucket:
    Name: teligent-local-deployment

Lambda:
  Environment:
    LOG_LEVEL: DEBUG
  LogRetentionInDays: 7

MonitoringConfigs:
  EventBusArn: arn:aws:events:us-east-1:000000000000:event-bus/teligent-master-local-MonitoringEventBus
  WebhookUrl: "https://hooks.slack.com/services/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"

  Health:
    State: enabled
  GuardDuty:
    State: enabled
  CloudwatchLogs:
    State: disabled
    Default:
      LogGroups: "/aws/lambda/test-function," # String of log group names separated by commas or *
      Query: |
        fields @message, @logStream, @log
        | filter @message like /(?i)(error|fail|exception)/
        | sort @timestamp desc
        | limit 200
      Schedule: rate(15 minutes)
    Custom: []
