Region: us-east-1
Profile: neos

# AWS Services
IAM:
  DeploymentRole: arn:aws:iam::728171922033:role/teligent-DeploymentRole

S3:
  DeploymentBucket:
    Name: teligent-neos-deployment

Lambda:
  Environment:
    LOG_LEVEL: DEBUG
  LogRetentionInDays: 7

MonitoringConfigs:
  EventBusArn: arn:aws:events:us-east-1:728171922033:event-bus/teligent-master-neos-MonitoringEventBus
  SlackWebhookUrl: "https://hooks.slack.com/services/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"

  MonitorOptions:
    Health:
      Enabled: true
    CloudwatchLogs:
      Enabled: true
      LogGroups:
        - teligent-neos-test
      Query: |
        fields @message, @logStream, @log
        | filter @message like /(?i)(error|fail|exception)/
        | sort @timestamp desc
        | limit 200
