IOTStreamQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-${self:provider.stage}-IOTStreams
    # FifoQueue: true
    # ContentBasedDeduplication: false
    RedrivePolicy:
      deadLetterTargetArn: !GetAtt IOTStreamDLQ.Arn
      maxReceiveCount: 1
    VisibilityTimeout: 600
    Tags:
      - Key: Owner
        Value: ${self:service}
      - Key: Environment
        Value: ${self:provider.stage}


MonitorCase123Queue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-${self:provider.stage}-MonitorCase123
    RedrivePolicy:
      deadLetterTargetArn: !GetAtt MonitorDLQ.Arn
      maxReceiveCount: 1
    VisibilityTimeout: 600
    Tags:
      - Key: Owner
        Value: ${self:service}
      - Key: Environment
        Value: ${self:provider.stage}


MonitorCase4Queue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-${self:provider.stage}-MonitorCase4
    RedrivePolicy:
      deadLetterTargetArn: !GetAtt MonitorDLQ.Arn
      maxReceiveCount: 1
    VisibilityTimeout: 600
    Tags:
      - Key: Owner
        Value: ${self:service}
      - Key: Environment
        Value: ${self:provider.stage}


MonitorCase5Queue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-${self:provider.stage}-MonitorCase5
    RedrivePolicy:
      deadLetterTargetArn: !GetAtt MonitorDLQ.Arn
      maxReceiveCount: 1
    VisibilityTimeout: 600
    Tags:
      - Key: Owner
        Value: ${self:service}
      - Key: Environment
        Value: ${self:provider.stage}


MonitorCase6Queue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-${self:provider.stage}-MonitorCase6
    RedrivePolicy:
      deadLetterTargetArn: !GetAtt MonitorDLQ.Arn
      maxReceiveCount: 1
    VisibilityTimeout: 600
    Tags:
      - Key: Owner
        Value: ${self:service}
      - Key: Environment
        Value: ${self:provider.stage}


MonitorCase7Queue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-${self:provider.stage}-MonitorCase7
    RedrivePolicy:
      deadLetterTargetArn: !GetAtt MonitorDLQ.Arn
      maxReceiveCount: 1
    VisibilityTimeout: 600
    Tags:
      - Key: Owner
        Value: ${self:service}
      - Key: Environment
        Value: ${self:provider.stage}


NotificationQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-${self:provider.stage}-Notifications
    RedrivePolicy:
      deadLetterTargetArn: !GetAtt NotificationDLQ.Arn
      maxReceiveCount: 1
    VisibilityTimeout: 600
    Tags:
      - Key: Owner
        Value: ${self:service}
      - Key: Environment
        Value: ${self:provider.stage}


# ------------------------------------------------------------------------------
IOTStreamDLQ:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-${self:provider.stage}-IOTStreamDLQ
    Tags:
      - Key: Owner
        Value: ${self:service}
      - Key: Environment
        Value: ${self:provider.stage}


DynamoStreamDLQ:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-${self:provider.stage}-DynamoStreamDLQ
    Tags:
      - Key: Owner
        Value: ${self:service}
      - Key: Environment
        Value: ${self:provider.stage}


MonitorDLQ:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-${self:provider.stage}-MonitorDLQ


NotificationDLQ:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-${self:provider.stage}-NotificationDLQ
    Tags:
      - Key: Owner
        Value: ${self:service}
      - Key: Environment
        Value: ${self:provider.stage}


# ------------------------------------------------------------------------------
IOTStreamQueuePolicy:
  Type: AWS::SQS::QueuePolicy
  Properties:
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Sid: AllowIOTCore
          Effect: Allow
          Principal:
            Service: iot.amazonaws.com
          Action:
            - sqs:SendMessage
          Resource: !GetAtt IOTStreamQueue.Arn
    Queues:
      - !Ref IOTStreamQueue


MonitorQueuePolicy:
  Type: AWS::SQS::QueuePolicy
  Properties:
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Sid: AllowLambda
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
            - sqs:Get*
            - sqs:Send*
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:ChangeMessageVisibility
          Resource:
            - !GetAtt IOTStreamQueue.Arn
            - !GetAtt MonitorCase123Queue.Arn
            - !GetAtt MonitorCase4Queue.Arn
            - !GetAtt MonitorCase5Queue.Arn
            - !GetAtt MonitorCase6Queue.Arn
            - !GetAtt MonitorCase7Queue.Arn
            - !GetAtt NotificationQueue.Arn
    Queues:
      - !Ref MonitorCase123Queue
      - !Ref MonitorCase4Queue
      - !Ref MonitorCase5Queue
      - !Ref MonitorCase6Queue
      - !Ref MonitorCase7Queue
      - !Ref NotificationQueue
