function:
  name: ${self:service}-${self:provider.stage}-AddTaskComment
  description: Add comment to task, triggered by API Gateway
  handler: src.entrypoints.apigw.tasks.main.handler
  events:
    - http:
        method: POST
        path: /tasks/{task_id}/comments
        cors: true
  environment:
    POWERTOOLS_SERVICE_NAME: tasks
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY, "dev-secret-key-change-in-production"}
    JWT_ALGORITHM: ${env:JWT_ALGORITHM, "HS256"}
