function:
  name: ${self:service}-${self:provider.stage}-CreateUser
  description: Create user (admin only), triggered by API Gateway
  handler: src.entrypoints.apigw.routes.users.handler
  events:
    - http:
        method: POST
        path: /users
        cors: true
  environment:
    POWERTOOLS_SERVICE_NAME: users
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY, "dev-secret-key-change-in-production"}
    JWT_ALGORITHM: ${env:JWT_ALGORITHM, "HS256"}
    BCRYPT_ROUNDS: ${env:BCRYPT_ROUNDS, "12"}
