MonitoringEventRule:
  Type: AWS::Events::Rule
  Properties:
    Name: ${self:service}-MonitoringEventRule
    Description: Publish monitoring events to the master EventBus
    EventBusName: default
    EventPattern: |
      {
        "$or": [
          {
            "source": ["aws.guardduty", "aws.health"],
            "detail-type": ["GuardDuty Finding", "AWS Health Event"]
          },
          {
            "source": ["aws.cloudformation"],
            "detail-type": ["CloudFormation Stack Status Change"],
            "detail": {
              "status-details": {
                "status": [ { "wildcard": "*COMPLETE" }, { "wildcard": "*FAILED" }]
              },
              "stack-id": [{ "wildcard": "*stack/monitoring-agent*"}]
            }
          },
          {
            "source": [ { "wildcard": "monitoring.agent*" } ]
          }
        ]
      }
    State: enabled
    Targets:
      - Arn: ${self:custom.monitoringConfigs.EventBusArn}
        Id: ${self:service}-MonitoringEventBusTarget
        RoleArn: !GetAtt EventBridgeRole.Arn
        DeadLetterConfig:
          Arn: !GetAtt MonitoringEventRuleDLQ.Arn
