LambdaFunctionRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: ${self:service}-${self:provider.stage}-LambdaFunctionRole
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
    ManagedPolicyArns:
      - !Ref LambdaFunctionPolicy

LambdaFunctionPolicy:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    ManagedPolicyName: ${self:service}-${self:provider.stage}-LambdaFunctionPolicy
    PolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Sid: AllowCloudwatchLogs
          Effect: Allow
          Action:
            - logs:CreateLogStream
            - logs:CreateLogGroup
            - logs:PutLogEvents
          Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/monitoring*:*"
        - Sid: AllowQueryLogsInsights
          Effect: Allow
          Action:
            - logs:StartQuery
            - logs:GetQueryResults
          Resource: [
            !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*",
            !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*"
          ]
        - Sid: AllowSendMessagesToSQS
          Effect: Allow
          Action:
            - sqs:Get*
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:ChangeMessageVisibility
          Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:monitoring*"
        - Sid: AllowPublishToEventBus
          Effect: Allow
          Action:
            - events:PutEvents
          Resource: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/default"
        - Sid: ECSReadOnlyAccess
          Effect: Allow
          Action:
            - ecs:List*
            - ecs:Describe*
          Resource: "*"
        - Sid: LambdaReadOnlyAccess
          Effect: Allow
          Action:
            - lambda:List*
            - lambda:Get*
          Resource: "*"

# EventBridgeRole, that allows the Lambda function to be triggered by EventBridge events
EventBridgeRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: ${self:service}-${self:provider.stage}-EventBridgeRole
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: sts:AssumeRole
    ManagedPolicyArns:
      - !Ref EventBridgePolicy

EventBridgePolicy:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    ManagedPolicyName: ${self:service}-${self:provider.stage}-EventBridgePolicy
    PolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Sid: AllowInvokeLambdaFunctions
          Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:monitoring*:*"
        - Sid: AllowPublishEventsToEventBus
          Effect: Allow
          Action:
            - events:PutEvents
          Resource: !Sub "arn:aws:events:${AWS::Region}:*:event-bus/monitoring*"
