function:
  name: ${self:service}-${self:provider.stage}-StartFirmwareUpdate
  description: Update the firmware version of the device
  handler: src.handlers.update_firmware.start_firmware_update.main.handler
  timeout: 60
  package:
    patterns:
      - src/handlers/update_firmware/start_firmware_update/*.py
      - src/models/*.py
      - src/repositories/*.py
      - src/services/iot_core.py
      - src/services/devices.py
      - src/services/storage.py
      - src/*.py
      - "!src/templates.py"
  maximumRetryAttempts: 0
  vpc:
    securityGroupIds: ${self:custom.VPC.SecurityGroupIds}
    subnetIds: ${self:custom.VPC.PrivateSubnetIds}
  environment:
    FUNTION_NAME: ${self:service}-${self:provider.stage}-StartFirmwareUpdate
